"""add payout processing fields

Revision ID: 1ca6f9ac3b48
Revises: 27e04c827004
Create Date: 2026-09-24 06:45:48.862553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca6f9ac3b48'
down_revision = '27e04c827004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_payout_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_payout_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payout_error', sa.String(length=1000), nullable=True))
        batch_op.create_index(batch_op.f('ix_driver_payout_requests_razorpay_payout_id'), ['razorpay_payout_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_payout_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_payout_requests_razorpay_payout_id'))
        batch_op.drop_column('payout_error')
        batch_op.drop_column('razorpay_payout_id')

    # ### end Alembic commands ###
