"""add driver payout method

Revision ID: 27e04c827004
Revises: 987c3e3d77b5
Create Date: 2026-09-23 18:17:40.609830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e04c827004'
down_revision = '987c3e3d77b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_holder_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('bank_ifsc_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account_holder_name')
        batch_op.drop_column('payout_method')

    # ### end Alembic commands ###
