"""add payment records

Revision ID: 49af817b6aec
Revises: 8bcba36c9ebe
Create Date: 2026-09-23 09:31:32.682286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49af817b6aec'
down_revision = '8bcba36c9ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
