"""add operator routing to driver payout requests

Revision ID: 6e0d689956bc
Revises: 1ca6f9ac3b48
Create Date: 2026-09-24 10:25:17.105080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e0d689956bc'
down_revision = '1ca6f9ac3b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_payout_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('operator_note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('operator_processed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_driver_payout_requests_operator_id'), ['operator_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_payout_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_driver_payout_requests_operator_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('operator_processed_at')
        batch_op.drop_column('operator_note')
        batch_op.drop_column('operator_id')

    # ### end Alembic commands ###
