"""Add missing customer fields

Revision ID: 7e1aeb297adf
Revises: a2b3c4d5e6f7
Create Date: 2026-09-11 15:18:18.295252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1aeb297adf'
down_revision = 'a2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_public_id'), ['public_id'], unique=True)

    op.create_table('notification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_tokens_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_tokens_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('public_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=80), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('public_id'))
        batch_op.create_index(batch_op.f('ix_subscriptions_public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('public_id'))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('public_id'))

    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('public_id'))
        batch_op.create_index(batch_op.f('ix_verification_documents_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_documents_public_id'))
        batch_op.create_index(batch_op.f('public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_public_id'))
        batch_op.create_index(batch_op.f('public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('id_number')
        batch_op.drop_column('id_type')
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('notification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_notification_tokens_public_id'))
        batch_op.drop_index(batch_op.f('ix_notification_tokens_is_active'))

    op.drop_table('notification_tokens')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_public_id'))
        batch_op.drop_index(batch_op.f('ix_locations_city'))

    op.drop_table('locations')
    # ### end Alembic commands ###
