"""add operator wallets

Revision ID: 987c3e3d77b5
Revises: 49af817b6aec
Create Date: 2026-09-23 14:31:02.858274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987c3e3d77b5'
down_revision = '49af817b6aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_wallet_transactions_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_wallet_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_operator_wallet_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_wallet_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operator_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)

    with op.batch_alter_table('operator_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_wallets_operator_id'), ['operator_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_operator_wallets_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_wallets_public_id'))
        batch_op.drop_index(batch_op.f('ix_operator_wallets_operator_id'))

    with op.batch_alter_table('operator_wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_wallet_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_operator_wallet_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_operator_wallet_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_operator_wallet_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_operator_wallet_transactions_operator_id'))

    # ### end Alembic commands ###
