"""Initial models

Revision ID: b4f0d8cd5667
Revises: 
Create Date: 2026-09-04 17:50:02.934882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f0d8cd5667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('passenger', 'driver', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('total_rides', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_public_id'), ['public_id'], unique=True)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('license_photo_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', 'suspended', name='driver_verification_status'), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('availability', sa.Enum('online', 'offline', 'on_trip', name='driver_availability'), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_availability'), ['availability'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_verification_status'), ['verification_status'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.Enum('sedan', 'suv', 'hatchback', 'mini_van', name='vehicle_type'), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('rc_document_url', sa.String(length=500), nullable=True),
    sa.Column('insurance_document_url', sa.String(length=500), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_public_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_driver_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_verification_status'))
        batch_op.drop_index(batch_op.f('ix_drivers_public_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_availability'))

    op.drop_table('drivers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_public_id'))

    op.drop_table('customers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
